#pragma once 
#include <stdint.h>
#include <Renderer/Renderer.h>
#include <Renderer/RenderFence.h>

/**
 * @brief Singleton that handles frame count keeping for both the render thread and main thread, and handles their synchronization.
*/
class FrameManager {
public:

	/**
	 * @brief Singleton initialization
	*/
	static void Initialize();
	/**
	 * @brief Singleton getter
	*/
	static FrameManager* Get();
	/**
	 * @brief Singleton Destructor
	*/
	static void Shutdown();

public:

	/**
	 * @brief called by mainthread on a new frame to synchronize with the render thread and increment frame counter
	*/
	void StartFrame();

	/**
	 * @brief Get the frame number currently generated by the mainthread
	*/
	uint32_t GetCurrentFrameNumber() const {
		return frame_number;
	}

	/**
	 * @brief Get the frame number currently rendered by the render thread (render thread is always behind)
	*/
	uint32_t GetRendererFrameNumber() const {
		return m_Sync_Fence->GetValue();
	}

	/**
	 * @brief Get maximum number of frames the main thread is allowed to be ahead of the render thread before it waits
	 * 
	 * Can be set in the config file as property Latency_Frames, higher number usually means smoother framerates, but higher latency and memory usage.
	*/
	uint32_t GetLatencyFrames() const {
		return latency;
	}

private:
	static FrameManager* instance; ///< Singleton instance
	FrameManager();
	~FrameManager();

private:
	uint32_t frame_number = 0; ///< current frame number on the mainthread
	uint32_t latency = 0; ///< latency frames @see FrameManager::GetLatencyFrames
	std::shared_ptr<RenderFence> m_Sync_Fence; ///< Fence used to synchronize with the render thread.

};